import { Template, Transaction, Goal } from './types';
import { LayoutDashboard, Wallet, PiggyBank, Plane, Calculator, Video, TrendingUp, BookOpen, CreditCard, FileText } from 'lucide-react';

export const SUPPORTED_LANGUAGES = [
  { code: 'en', label: 'English', flag: '🇺🇸' },
  { code: 'de', label: 'Deutsch', flag: '🇩🇪' },
  { code: 'tr', label: 'Türkçe', flag: '🇹🇷' },
];

export const TRANSLATIONS = {
  en: {
    greeting: 'Good evening',
    totalIncome: 'Total Income',
    totalExpenses: 'Total Expenses',
    netSavings: 'Net Savings',
    savingsRate: 'Savings Rate',
    goalProgress: 'Goal Progress',
    activeGoals: 'Active Goals',
    quickActions: 'Quick Actions',
    createTemplate: 'Create Template',
    addTransaction: 'Add Transaction',
    setGoal: 'Set Goal',
    uploadDoc: 'Upload Document',
    recentActivity: 'Recent Activities',
    dashboard: 'Dashboard',
    library: 'Library',
    trash: 'Trash',
    login: 'Login',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    welcomeBack: 'Welcome Back',
    financialAdvisor: 'Financial Advisor (Live)',
    visualizeGoal: 'Visualize Goal (Veo)',
    smartAnalysis: 'Smart Analysis',
    generateImage: 'Generate Image',
  },
  de: {
    greeting: 'Guten Abend',
    totalIncome: 'Gesamteinkommen',
    totalExpenses: 'Gesamtausgaben',
    netSavings: 'Nettoersparnis',
    savingsRate: 'Sparquote',
    goalProgress: 'Zielerreichung',
    activeGoals: 'Aktive Ziele',
    quickActions: 'Schnellaktionen',
    createTemplate: 'Vorlage erstellen',
    addTransaction: 'Transaktion hinzufügen',
    setGoal: 'Ziel setzen',
    uploadDoc: 'Dokument hochladen',
    recentActivity: 'Letzte Aktivitäten',
    dashboard: 'Instrumententafel',
    library: 'Bibliothek',
    trash: 'Papierkorb',
    login: 'Anmelden',
    register: 'Registrieren',
    email: 'E-Mail',
    password: 'Passwort',
    welcomeBack: 'Willkommen zurück',
    financialAdvisor: 'Finanzberater (Live)',
    visualizeGoal: 'Ziel visualisieren (Veo)',
    smartAnalysis: 'Intelligente Analyse',
    generateImage: 'Bild generieren',
  },
  tr: {
    greeting: 'İyi akşamlar',
    totalIncome: 'Toplam Gelir',
    totalExpenses: 'Toplam Gider',
    netSavings: 'Net Tasarruf',
    savingsRate: 'Tasarruf Oranı',
    goalProgress: 'Hedef İlerlemesi',
    activeGoals: 'Aktif Hedefler',
    quickActions: 'Hızlı İşlemler',
    createTemplate: 'Şablon Oluştur',
    addTransaction: 'İşlem Ekle',
    setGoal: 'Hedef Belirle',
    uploadDoc: 'Belge Yükle',
    recentActivity: 'Son Aktiviteler',
    dashboard: 'Kontrol Paneli',
    library: 'Kütüphane',
    trash: 'Çöp Kutusu',
    login: 'Giriş Yap',
    register: 'Kayıt Ol',
    email: 'E-posta',
    password: 'Şifre',
    welcomeBack: 'Tekrar Hoşgeldiniz',
    financialAdvisor: 'Finans Danışmanı (Canlı)',
    visualizeGoal: 'Hedefi Görselleştir (Veo)',
    smartAnalysis: 'Akıllı Analiz',
    generateImage: 'Resim Oluştur',
  },
};

export const MOCK_TRANSACTIONS: Transaction[] = [
  { id: '1', date: '2023-10-25T14:30:00', description: 'Freelance Payment', amount: 12500, type: 'income', category: 'Salary' },
  { id: '2', date: '2023-10-24T09:15:00', description: 'Grocery Market', amount: 850, type: 'expense', category: 'Food' },
  { id: '3', date: '2023-10-23T18:45:00', description: 'Netflix Subscription', amount: 120, type: 'expense', category: 'Entertainment' },
  { id: '4', date: '2023-10-22T12:00:00', description: 'Gas Station', amount: 1500, type: 'expense', category: 'Transport' },
];

export const INITIAL_GOALS: Goal[] = [
  { id: '1', title: 'Emergency Fund', currentAmount: 3500, targetAmount: 10000, currency: '₺', type: 'savings' },
  { id: '2', title: 'Vacation Savings', currentAmount: 800, targetAmount: 2500, currency: '₺', type: 'savings' },
];

export const INITIAL_TEMPLATES: Template[] = [
  { id: '1', title: 'Monthly Budget', icon: 'LayoutDashboard', type: 'budget', isSaved: true, isInTrash: false },
  { id: '2', title: 'Budget Guide', icon: 'BookOpen', type: 'guide', isSaved: false, isInTrash: false },
  { id: '3', title: 'Emergency Fund', icon: 'PiggyBank', type: 'budget', isSaved: true, isInTrash: false },
  { id: '4', title: 'Vacation Savings', icon: 'Plane', type: 'budget', isSaved: true, isInTrash: false },
  { id: '5', title: 'Retirement Calculator', icon: 'Calculator', type: 'calculator', isSaved: false, isInTrash: false },
  { id: '6', title: 'Emergency Fund Video', icon: 'Video', type: 'video', isSaved: false, isInTrash: false },
  { id: '7', title: 'Investment Portfolio', icon: 'TrendingUp', type: 'portfolio', isSaved: false, isInTrash: false },
  { id: '8', title: 'Investment Basics', icon: 'BookOpen', type: 'guide', isSaved: false, isInTrash: false },
  { id: '9', title: 'Debt Payment', icon: 'CreditCard', type: 'budget', isSaved: false, isInTrash: false },
  { id: '10', title: 'Tax Planning Guide', icon: 'FileText', type: 'guide', isSaved: false, isInTrash: false },
];
