import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'tr' | 'en' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
  currency: string;
  resetKey: number;
  convertToDisplayCurrency?: (amount: number) => number;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  tr: {
    // Navigation
    'nav.home': 'Ana Sayfa',
    'nav.features': 'Özellikler',
    'nav.stats': 'İstatistikler',
    'nav.testimonials': 'Yorumlar',
    'nav.contact': 'İletişim',
    'nav.login': 'Giriş Yap',
    'nav.signup': 'Kayıt Ol',
    'nav.logout': 'Çıkış Yap',
    'nav.dashboard': 'Kontrol Paneli',
    'nav.settings': 'Ayarlar',

    // Hero Section
    'hero.title.1': 'Akıllı',
    'hero.title.2': 'Tasarruf',
    'hero.title.3': 'ile Geleceğini',
    'hero.title.4': 'Şekillendir',
    'hero.description': 'Yapay zeka destekli finansal yönetim platformu ile bütçeni optimize et, hedeflerine ulaş.',
    'hero.cta': 'Ücretsiz Başla',
    'hero.dashboard': 'Kontrol Paneli',
    'hero.dashboard.title': 'Tasarruf İlerlemen',
    'hero.dashboard.saved': 'Biriken',
    'hero.dashboard.target': 'Hedef',
    'hero.dashboard.progress': 'İlerleme',
    'hero.dashboard.completion': 'Tamamlanma',
    'hero.dashboard.days': 'gün',
    'hero.dashboard.dayProgress': 'Gün {day}: {currency}{amount} birikti',
    'hero.dashboard.todayAmount': 'Bugün: {currency}{amount}',

    // Features
    'features.title': 'Güçlü Özellikler',
    'features.subtitle': 'Finansal hedeflerinize ulaşmanız için ihtiyacınız olan her şey',
    'features.ai.title': 'Yapay Zeka Analizi',
    'features.ai.desc': 'Harcama alışkanlıklarınızı analiz eder ve kişiselleştirilmiş öneriler sunar',
    'features.analysis.title': 'Detaylı Analiz',
    'features.analysis.desc': 'Gelir ve giderlerinizi kategorilere ayırarak detaylı raporlar oluşturur',
    'features.goals.title': 'Hedef Takibi',
    'features.goals.desc': 'Tasarruf hedeflerinizi belirleyin ve ilerlemenizi takip edin',
    'features.notifications.title': 'Akıllı Bildirimler',
    'features.notifications.desc': 'Önemli finansal değişiklikler için zamanında uyarılar alın',
    'features.security.title': 'Güvenlik',
    'features.security.desc': 'Verileriniz 256-bit SSL şifreleme ile korunur',
    'features.mobile.title': 'Mobil Uyumlu',
    'features.mobile.desc': 'Her cihazdan erişilebilir, responsive tasarım',

    // Stats
    'stats.activeUsers': 'Aktif Kullanıcı',
    'stats.totalSavings': 'Toplam Tasarruf',
    'stats.customerSatisfaction': 'Müşteri Memnuniyeti',
    'stats.supportService': 'Destek Hizmeti',

    // Testimonials
    'testimonials.title': 'Kullanıcı Yorumları',
    'testimonials.subtitle': 'Binlerce kullanıcı Sparlo.ai ile finansal hedeflerine ulaştı',
    'testimonials.1.name': 'Ayşe Yılmaz',
    'testimonials.1.role': 'Pazarlama Uzmanı',
    'testimonials.1.content': 'Sparlo.ai sayesinde aylık 2000₺ tasarruf etmeyi başardım. Yapay zeka önerileri gerçekten işe yarıyor!',
    'testimonials.2.name': 'Mehmet Kaya',
    'testimonials.2.role': 'Yazılım Geliştirici',
    'testimonials.2.content': 'Harcamalarımı takip etmek hiç bu kadar kolay olmamıştı. Hedeflerime ulaşmak artık çok daha mümkün.',
    'testimonials.3.name': 'Zeynep Demir',
    'testimonials.3.role': 'Öğretmen',
    'testimonials.3.content': 'Kullanıcı dostu arayüzü ve detaylı analizleri ile finansal durumumu çok daha iyi anlıyorum.',

    // CTA
    'cta.title.1': 'Finansal Geleceğini',
    'cta.title.2': 'Bugün Şekillendir',
    'cta.description': 'Sparlo.ai ile akıllı tasarrufa başla. İlk 30 gün tamamen ücretsiz, kredi kartı gerektirmez.',
    'cta.start': 'Ücretsiz Dene',
    'cta.chat': 'Canlı Destek',
    'cta.free': 'Ücretsiz 30 Gün',
    'cta.nocard': 'Kredi Kartı Yok',
    'cta.instant': 'Anında Kurulum',

    // Footer
    'footer.description': 'Yapay zeka destekli akıllı tasarruf platformu ile finansal hedeflerinize ulaşın.',
    'footer.pricing': 'Fiyatlandırma',
    'footer.contact': 'İletişim',
    'footer.live': 'Canlı Destek',
    'footer.help': 'Yardım Merkezi',
    'footer.rights': 'Tüm hakları saklıdır.',
    'footer.privacy': 'Gizlilik',
    'footer.terms': 'Şartlar',
    'footer.cookies': 'Çerezler',
    'footer.tagline': 'Herkes İçin Akıllı Finansal Yönetim',

    // Blog
    'blog.financialTips': 'Finansal İpuçları',
    'blog.education': 'Eğitim',
    'blog.news': 'Haberler ve Güncellemeler',

    // Pricing
    'pricing.free': 'Ücretsiz Plan',
    'pricing.premium': 'Premium',

    // Login
    'login.title': 'Hesabına Giriş Yap',
    'login.subtitle': 'Finansal yolculuğuna devam et',
    'login.email': 'E-posta Adresi',
    'login.emailPlaceholder': 'ornek@email.com',
    'login.password': 'Şifre',
    'login.passwordPlaceholder': 'Şifrenizi girin',
    'login.remember': 'Beni hatırla',
    'login.forgot': 'Şifremi unuttum',
    'login.submit': 'Giriş Yap',
    'login.loading': 'Giriş yapılıyor...',
    'login.or': 'veya',
    'login.google': 'Google ile giriş yap',
    'login.facebook': 'Facebook ile giriş yap',
    'login.noAccount': 'Hesabın yok mu?',
    'login.register': 'Kayıt ol',
    'login.success': 'Başarıyla giriş yaptınız!',
    'login.emailNotFound': 'Bu e-posta adresi kayıtlı değil.',

    // Register
    'register.title': 'Hesap Oluştur',
    'register.subtitle': 'Finansal özgürlük yolculuğuna başla',
    'register.firstName': 'Ad',
    'register.firstNamePlaceholder': 'Adınız',
    'register.lastName': 'Soyad',
    'register.lastNamePlaceholder': 'Soyadınız',
    'register.email': 'E-posta Adresi',
    'register.emailPlaceholder': 'ornek@email.com',
    'register.password': 'Şifre',
    'register.passwordPlaceholder': 'Güçlü bir şifre oluşturun',
    'register.confirmPassword': 'Şifre Tekrar',
    'register.confirmPasswordPlaceholder': 'Şifrenizi tekrar girin',
    'register.terms': 'Kabul ediyorum',
    'register.termsLink': 'Kullanım Şartları',
    'register.and': 've',
    'register.privacyLink': 'Gizlilik Politikası',
    'register.submit': 'Hesap Oluştur',
    'register.loading': 'Hesap oluşturuluyor...',
    'register.or': 'veya',
    'register.google': 'Google ile kayıt ol',
    'register.facebook': 'Facebook ile kayıt ol',
    'register.hasAccount': 'Zaten hesabın var mı?',
    'register.login': 'Giriş yap',
    'register.success': 'Hesabınız başarıyla oluşturuldu!',
    'register.emailExists': 'Bu e-posta adresi zaten kayıtlı.',
    'register.passwordMismatch': 'Şifreler eşleşmiyor.',
    'register.acceptTerms': 'Lütfen kullanım şartlarını kabul edin.',

    // Forgot Password
    'forgot.title': 'Şifremi Unuttum',
    'forgot.subtitle': 'Şifre sıfırlama bağlantısı gönderelim',
    'forgot.email': 'E-posta Adresi',
    'forgot.emailPlaceholder': 'Kayıtlı e-posta adresiniz',
    'forgot.submit': 'Sıfırlama Bağlantısı Gönder',
    'forgot.loading': 'Gönderiliyor...',
    'forgot.backToLogin': 'Giriş sayfasına dön',
    'forgot.successTitle': 'E-posta Gönderildi',
    'forgot.successMessage': 'Şifre sıfırlama bağlantısı e-posta adresinize gönderildi.',
    'forgot.autoClose': 'Bu pencere otomatik olarak kapanacak...',

    // Partnership
    'partnership.title': 'Güvenilir Ortaklarımız',
    'partnership.subtitle': 'Finansal güvenliğiniz için sektörün lider kurumlarıyla çalışıyoruz',
    'partnership.trustedPartners': 'Güvenilir Ortaklar',
    'partnership.achievements': 'Başarılarımız',
    'partnership.activeUsers': 'Aktif Kullanıcı',
    'partnership.totalSavings': 'Toplam Tasarruf',
    'partnership.uptime': 'Çalışma Süresi',
    'partnership.support': 'Destek',
    'partnership.trustIndicators': 'Güven Göstergeleri',
    'partnership.bankLevel': 'Banka Seviyesi Güvenlik',
    'partnership.certified': 'Sertifikalı Platform',
    'partnership.encrypted': 'Şifrelenmiş Veriler',
    'partnership.awardWinning': 'Ödüllü Hizmet',

    // Workspace
    'workspace.workspace': 'Çalışma Alanı',
    'workspace.home': 'Ana Sayfa',
    'workspace.dashboard': 'Kontrol Paneli',
    'workspace.templates': 'Şablonlar',
    'workspace.videos': 'Videolar',
    'workspace.trash': 'Çöp Kutusu',
    'workspace.library': 'Kütüphane',
    'workspace.profile': 'Profil',
    'workspace.pleaseLogin': 'Lütfen Giriş Yapın',
    'workspace.loginRequired': 'Çalışma alanına erişmek için giriş yapmanız gerekiyor',
    'workspace.searchPlaceholder': 'Ara...',
    'workspace.notifications': 'Bildirimler',
    'workspace.viewAllNotifications': 'Tüm bildirimleri görüntüle',
    'workspace.newTemplate': 'Yeni Şablon',
    'workspace.profileSettings': 'Profil Ayarları',
    'workspace.accountSettings': 'Hesap Ayarları',
    'workspace.preferences': 'Tercihler',
    'workspace.logout': 'Çıkış Yap',
    'workspace.goToHomePage': 'Ana sayfaya git',
    'workspace.clickToGoHome': 'Ana sayfaya dönmek için tıklayın',
    'workspace.backToHomePage': 'Ana Sayfaya Geri Dön',

    // Workspace Home
    'workspace.overviewProgress': 'İlerlemenize genel bakış ve son aktiviteleriniz',
    'workspace.whereLeftOff': 'Kaldığınız Yer',
    'workspace.lastActivity': 'Son Aktivite',
    'workspace.budgetReview': 'Bütçe incelemesi tamamlandı',
    'workspace.progressUpdate': 'İlerleme Güncellemesi',
    'workspace.improvementThisMonth': 'bu ay iyileşme',
    'workspace.comparedToLastMonth': 'geçen aya göre',
    'workspace.nextRecommendation': 'Sonraki Öneri',
    'workspace.reviewExpenseCategories': 'Harcama kategorilerini gözden geçirin',
    'workspace.viewDetails': 'Detayları Görüntüle',
    'workspace.monthlyProgress': 'Aylık İlerleme',
    'workspace.savingsProgress': 'Tasarruf İlerlemesi',
    'workspace.goalAchievement': 'Hedef Başarısı',
    'workspace.budgetAdherence': 'Bütçe Uyumu',
    'workspace.weeklyInsights': 'Haftalık İçgörüler',
    'workspace.achievements': 'Başarılar',
    'workspace.firstGoalSet': 'İlk Hedef Belirlendi',
    'workspace.completedToday': 'Bugün tamamlandı',
    'workspace.savingsStreak': 'Tasarruf Serisi',
    'workspace.daysInARow': 'gün üst üste',
    'workspace.budgetExpert': 'Bütçe Uzmanı',
    'workspace.under5Budgets': '5 bütçe altında',
    'workspace.quickStats': 'Hızlı İstatistikler',
    'workspace.totalTransactions': 'Toplam İşlem',
    'workspace.activeGoals': 'Aktif Hedefler',
    'workspace.avgMonthlySavings': 'Ort. Aylık Tasarruf',
    'workspace.bestSavingsMonth': 'En İyi Tasarruf Ayı',
    'workspace.thisMonth': 'Bu Ay',
    'workspace.quickActions': 'Hızlı İşlemler',
    'workspace.newTemplateCreated': 'Yeni şablon oluşturuldu',
    'workspace.budgetTemplateCreated': 'Bütçe şablonu oluşturuldu',
    'workspace.createTemplate': 'Şablon oluştur',
    'workspace.addTransaction': 'İşlem Ekle',
    'workspace.trackExpense': 'Harcama takibi',
    'workspace.transactionAdded': 'İşlem eklendi',
    'workspace.expenseTracked': 'Harcama kaydedildi',
    'workspace.setGoal': 'Hedef Belirle',
    'workspace.planSavings': 'Tasarruf planla',
    'workspace.goalSet': 'Hedef belirlendi',
    'workspace.savingsGoalCreated': 'Tasarruf hedefi oluşturuldu',
    'workspace.addDocument': 'Belge Ekle',
    'workspace.uploadFile': 'Dosya yükle',
    'workspace.documentAdded': 'Belge eklendi',
    'workspace.fileUploaded': 'Dosya yüklendi',
    'workspace.recentActivities': 'Son Aktiviteler',
    'workspace.noRecentActivities': 'Henüz aktivite yok',
    'workspace.activitiesThisWeek': 'Bu Hafta Aktivite',
    'workspace.templatesUsed': 'Kullanılan Şablon',
    'workspace.documentsManaged': 'Yönetilen Belge',
    'workspace.justNow': 'Az önce',
    'workspace.minutesAgo': 'dakika önce',
    'workspace.hoursAgo': 'saat önce',
    'workspace.daysAgo': 'gün önce',

    // Homepage Sections in Workspace
    'workspace.heroSection': 'Ana Bölüm',
    'workspace.heroSectionDesc': 'Platform tanıtımı ve ana özellikler',
    'workspace.featuresSection': 'Özellikler',
    'workspace.featuresSectionDesc': 'Platform özelliklerinin detaylı açıklaması',
    'workspace.statsSection': 'İstatistikler',
    'workspace.statsSectionDesc': 'Platform kullanım istatistikleri',
    'workspace.partnershipSection': 'Ortaklıklar',
    'workspace.partnershipSectionDesc': 'Güvenilir iş ortaklarımız',
    'workspace.testimonialsSection': 'Kullanıcı Yorumları',
    'workspace.testimonialsSectionDesc': 'Memnun kullanıcılarımızın deneyimleri',
    'workspace.ctaSection': 'Harekete Geçirici Çağrı',
    'workspace.ctaSectionDesc': 'Platforma katılım için teşvik edici içerik',

    // Templates
    'templates.title': 'Şablon Galerisi',
    'templates.subtitle': 'Finansal hedefleriniz için hazır şablonlar',
    'templates.all': 'Tümü',
    'templates.budget': 'Bütçe',
    'templates.savings': 'Tasarruf',
    'templates.expense': 'Harcama',
    'templates.investment': 'Yatırım',
    'templates.custom': 'Özel',
    'templates.createNew': 'Yeni Şablon Oluştur',
    'templates.restoreHidden': 'Gizli Şablonları Geri Yükle',
    'templates.noHiddenTemplates': 'Gizli şablon bulunmuyor.',
    'templates.confirmRestoreHidden': 'Gizli şablonları geri yüklemek istediğinizden emin misiniz?',
    'templates.noTemplates': 'Şablon bulunamadı',
    'templates.createFirstTemplate': 'İlk şablonunuzu oluşturun',
    'templates.templateName': 'Şablon Adı',
    'templates.templateNamePlaceholder': 'Şablon adını girin',
    'templates.description': 'Açıklama',
    'templates.descriptionPlaceholder': 'Şablon açıklamasını girin',
    'templates.category': 'Kategori',
    'templates.create': 'Oluştur',
    'templates.cancel': 'İptal',
    'templates.useTemplate': 'Şablonu Kullan',
    'templates.usingTemplate': 'Şablon kullanılıyor',
    'templates.deleteTemplate': 'Şablonu sil',
    'templates.hideTemplate': 'Şablonu gizle',
    'templates.confirmDelete': 'Bu şablonu silmek istediğinizden emin misiniz?',
    'templates.confirmDeletePredefined': 'Bu önceden tanımlanmış şablonu gizlemek istediğinizden emin misiniz? (Daha sonra geri yükleyebilirsiniz)',

    // Predefined Templates
    'templates.monthlyBudget': 'Aylık Bütçe',
    'templates.monthlyBudgetDesc': 'Aylık gelir ve giderlerinizi takip edin',
    'templates.emergencyFund': 'Acil Durum Fonu',
    'templates.emergencyFundDesc': 'Beklenmedik durumlar için tasarruf yapın',
    'templates.vacationSavings': 'Tatil Tasarrufu',
    'templates.vacationSavingsDesc': 'Hayalinizdeki tatil için para biriktirin',
    'templates.expenseTracker': 'Harcama Takipçisi',
    'templates.expenseTrackerDesc': 'Günlük harcamalarınızı kategorilere ayırın',
    'templates.investmentPortfolio': 'Yatırım Portföyü',
    'templates.investmentPortfolioDesc': 'Yatırımlarınızı takip edin ve analiz edin',
    'templates.debtPayoff': 'Borç Ödeme',
    'templates.debtPayoffDesc': 'Borçlarınızı sistematik olarak ödeyin',

    // Trash
    'trash.title': 'Çöp Kutusu',
    'trash.subtitle': 'Silinen öğelerinizi buradan geri yükleyebilirsiniz',
    'trash.autoDeleteWarning': 'Öğeler 30 gün sonra otomatik olarak silinir',
    'trash.empty': 'Çöp kutusu boş',
    'trash.emptyDescription': 'Silinen öğeler burada görünecek',
    'trash.selected': 'seçili',
    'trash.selectAll': 'Tümünü seç',
    'trash.sortByDeleted': 'Silinme tarihine göre',
    'trash.sortByName': 'İsme göre',
    'trash.sortByExpiry': 'Son kullanma tarihine göre',
    'trash.restoreSelected': 'Seçilenleri Geri Yükle',
    'trash.deleteSelected': 'Seçilenleri Sil',
    'trash.emptyTrash': 'Çöp Kutusunu Boşalt',
    'trash.restore': 'Geri Yükle',
    'trash.deleteForever': 'Kalıcı Sil',
    'trash.restored': 'Geri yüklendi',
    'trash.confirmPermanentDelete': 'Bu öğeyi kalıcı olarak silmek istediğinizden emin misiniz?',
    'trash.confirmRestoreSelected': '{count} öğeyi geri yüklemek istediğinizden emin misiniz?',
    'trash.confirmDeleteSelected': '{count} öğeyi kalıcı olarak silmek istediğinizden emin misiniz?',
    'trash.confirmEmptyTrash': 'Çöp kutusunu tamamen boşaltmak istediğinizden emin misiniz?',
    'trash.deletedOn': 'Silinme:',
    'trash.expiresIn': 'Sona erme:',
    'trash.expired': 'Süresi doldu',
    'trash.days': 'gün',
    'trash.hours': 'saat',
    'trash.minutes': 'dakika',

    // Library
    'library.title': 'Kaynak Kütüphanesi',
    'library.subtitle': 'Finansal eğitim ve araçlar',
    'library.searchPlaceholder': 'Kaynaklarda ara...',
    'library.bookmarksOnly': 'Sadece yer imleri',
    'library.all': 'Tümü',
    'library.guides': 'Kılavuzlar',
    'library.templates': 'Şablonlar',
    'library.articles': 'Makaleler',
    'library.videos': 'Videolar',
    'library.tools': 'Araçlar',
    'library.noResults': 'Sonuç bulunamadı',
    'library.noItems': 'Henüz kaynak yok',
    'library.tryDifferentSearch': 'Farklı arama terimleri deneyin',
    'library.addFirstItem': 'İlk kaynağınızı ekleyin',
    'library.opening': 'Açılıyor',
    'library.addNewResource': 'Yeni Kaynak Ekle',
    'library.resourceTitle': 'Kaynak Başlığı',
    'library.resourceTitlePlaceholder': 'Kaynak başlığını girin',
    'library.description': 'Açıklama',
    'library.descriptionPlaceholder': 'Kaynak açıklamasını girin',
    'library.category': 'Kategori',
    'library.custom': 'Özel',
    'library.resourceType': 'Kaynak Türü',
    'library.typeLink': 'Bağlantı',
    'library.typePdf': 'PDF',
    'library.typeDoc': 'Belge',
    'library.typeVideo': 'Video',
    'library.typeImage': 'Resim',
    'library.typeSpreadsheet': 'Elektronik Tablo',
    'library.url': 'URL',
    'library.urlPlaceholder': 'https://example.com',
    'library.tags': 'Etiketler',
    'library.tagsPlaceholder': 'etiket1, etiket2, etiket3',
    'library.cancel': 'İptal',
    'library.create': 'Oluştur',
    'library.confirmDelete': 'Bu kaynağı silmek istediğinizden emin misiniz?',
    'library.confirmRemove': 'Bu kaynağı kütüphaneden kaldırmak istediğinizden emin misiniz?',
    'library.deleteItem': 'Kaynağı sil',
    'library.removeItem': 'Kaynağı kaldır',

    // Predefined Library Items
    'library.budgetingGuide': 'Bütçeleme Kılavuzu',
    'library.budgetingGuideDesc': 'Başlangıç seviyesi bütçe oluşturma rehberi',
    'library.investmentBasics': 'Yatırım Temelleri',
    'library.investmentBasicsDesc': 'Yatırım dünyasına giriş için temel bilgiler',
    'library.retirementCalculator': 'Emeklilik Hesaplayıcısı',
    'library.retirementCalculatorDesc': 'Emeklilik için ne kadar biriktirmeniz gerektiğini hesaplayın',
    'library.emergencyFundVideo': 'Acil Durum Fonu Videosu',
    'library.emergencyFundVideoDesc': 'Acil durum fonu oluşturma stratejileri',
    'library.taxPlanningGuide': 'Vergi Planlama Kılavuzu',
    'library.taxPlanningGuideDesc': 'Vergi avantajlarından nasıl yararlanacağınızı öğrenin',
    'library.debtPayoffTemplate': 'Borç Ödeme Şablonu',
    'library.debtPayoffTemplateDesc': 'Borçlarınızı sistematik olarak ödeme planı',

    // Financial Dashboard
    'finDash.totalIncome': 'Toplam Gelir',
    'finDash.totalExpense': 'Toplam Gider',
    'finDash.netSavings': 'Net Tasarruf',
    'finDash.goalsProgress': 'Hedef İlerlemesi',
    'finDash.thisMonth': 'Bu ay',
    'finDash.savingsRate': 'tasarruf oranı',
    'finDash.activeGoals': 'aktif hedef',
    'finDash.recentTransactions': 'Son İşlemler',
    'finDash.savingsGoals': 'Tasarruf Hedefleri',
    'finDash.high': 'Yüksek',
    'finDash.medium': 'Orta',
    'finDash.low': 'Düşük',
    'finDash.completed': 'tamamlandı',

    // Profile
    'profile.title': 'Kullanıcı Profili',
    'profile.subtitle': 'Hesap bilgilerinizi yönetin',
    'profile.personalInfo': 'Kişisel Bilgiler',
    'profile.password': 'Şifre',
    'profile.notifications': 'Bildirimler',
    'profile.privacy': 'Gizlilik',
    'profile.dataManagement': 'Veri Yönetimi',
    'profile.firstName': 'Ad',
    'profile.lastName': 'Soyad',
    'profile.email': 'E-posta',
    'profile.currentPassword': 'Mevcut Şifre',
    'profile.newPassword': 'Yeni Şifre',
    'profile.confirmPassword': 'Şifre Tekrar',
    'profile.saveChanges': 'Değişiklikleri Kaydet',
    'profile.changePassword': 'Şifreyi Değiştir',
    'profile.cancel': 'İptal',
    'profile.successMessage': 'Bilgileriniz başarıyla güncellendi',
    'profile.errorMessage': 'Bir hata oluştu, lütfen tekrar deneyin',
    'profile.passwordMismatch': 'Şifreler eşleşmiyor',
    'profile.passwordChangeSuccess': 'Şifreniz başarıyla değiştirildi',
    'profile.passwordChangeError': 'Şifre değiştirirken bir hata oluştu',
    'profile.emailNotifications': 'E-posta Bildirimleri',
    'profile.emailNotificationsDesc': 'Önemli güncellemeler için e-posta alın',
    'profile.pushNotifications': 'Push Bildirimleri',
    'profile.pushNotificationsDesc': 'Tarayıcı bildirimleri alın',
    'profile.marketingEmails': 'Pazarlama E-postaları',
    'profile.marketingEmailsDesc': 'Özel teklifler ve haberler alın',
    'profile.dataSharing': 'Veri Paylaşımı',
    'profile.dataSharingDesc': 'Anonim kullanım verilerini paylaş',
    'profile.analytics': 'Analitik',
    'profile.analyticsDesc': 'Deneyimi iyileştirmek için analitik veriler topla',
    'profile.deleteAccount': 'Hesabı Sil',
    'profile.deleteWarning': 'Bu işlem geri alınamaz. Tüm verileriniz silinecektir.',
    'profile.dataManagementDesc': 'Verilerinizi yönetin, dışa aktarın veya silin',
    'profile.resetData': 'Tüm Verileri Sıfırla',
    'profile.resetDataDesc': 'Bu işlem tüm finansal verilerinizi, şablonlarınızı ve ayarlarınızı siler.',
    'profile.resetDataWarning': 'Bu işlem geri alınamaz!',
    'profile.whatWillBeDeleted': 'Silinecek Veriler:',
    'profile.allTransactions': 'Tüm işlemler',
    'profile.allGoals': 'Tüm hedefler',
    'profile.dashboardStats': 'Kontrol paneli istatistikleri',
    'profile.activityHistory': 'Aktivite geçmişi',
    'profile.customTemplates': 'Özel şablonlar',
    'profile.libraryItems': 'Kütüphane öğeleri',
    'profile.trashItems': 'Çöp kutusu öğeleri',
    'profile.userSettings': 'Kullanıcı ayarları',
    'profile.resetConfirm': 'TÜM VERİLERİNİZİ SİLMEK İSTEDİĞİNİZDEN EMİN MİSİNİZ? Bu işlem geri alınamaz!',
    'profile.resetAllData': 'TÜM VERİLERİ SİFIRLA',
    'profile.resetSuccess': 'Tüm verileriniz başarıyla sıfırlandı',
    'profile.exportData': 'Verileri Dışa Aktar',
    'profile.exportDataDesc': 'Tüm verilerinizi JSON formatında indirin',
    'profile.exportDataButton': 'Verileri Dışa Aktar',
    'profile.importData': 'Verileri İçe Aktar',
    'profile.importDataDesc': 'Daha önce dışa aktardığınız verileri geri yükleyin',
    'profile.importDataButton': 'Verileri İçe Aktar',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.features': 'Features',
    'nav.stats': 'Stats',
    'nav.testimonials': 'Testimonials',
    'nav.contact': 'Contact',
    'nav.login': 'Login',
    'nav.signup': 'Sign Up',
    'nav.logout': 'Logout',
    'nav.dashboard': 'Dashboard',
    'nav.settings': 'Settings',

    // Hero Section
    'hero.title.1': 'Smart',
    'hero.title.2': 'Savings',
    'hero.title.3': 'Shape Your',
    'hero.title.4': 'Future',
    'hero.description': 'Optimize your budget and reach your goals with our AI-powered financial management platform.',
    'hero.cta': 'Start Free',
    'hero.dashboard': 'Dashboard',
    'hero.dashboard.title': 'Savings Progress',
    'hero.dashboard.saved': 'Saved',
    'hero.dashboard.target': 'Target',
    'hero.dashboard.progress': 'Progress',
    'hero.dashboard.completion': 'Completion',
    'hero.dashboard.days': 'days',
    'hero.dashboard.dayProgress': 'Day {day}: {currency}{amount} saved',
    'hero.dashboard.todayAmount': 'Today: {currency}{amount}',

    // Features
    'features.title': 'Powerful Features',
    'features.subtitle': 'Everything you need to reach your financial goals',
    'features.ai.title': 'AI Analysis',
    'features.ai.desc': 'Analyzes your spending habits and provides personalized recommendations',
    'features.analysis.title': 'Detailed Analysis',
    'features.analysis.desc': 'Creates detailed reports by categorizing your income and expenses',
    'features.goals.title': 'Goal Tracking',
    'features.goals.desc': 'Set your savings goals and track your progress',
    'features.notifications.title': 'Smart Notifications',
    'features.notifications.desc': 'Get timely alerts for important financial changes',
    'features.security.title': 'Security',
    'features.security.desc': 'Your data is protected with 256-bit SSL encryption',
    'features.mobile.title': 'Mobile Friendly',
    'features.mobile.desc': 'Accessible from any device with responsive design',

    // Stats
    'stats.activeUsers': 'Active Users',
    'stats.totalSavings': 'Total Savings',
    'stats.customerSatisfaction': 'Customer Satisfaction',
    'stats.supportService': 'Support Service',

    // Testimonials
    'testimonials.title': 'User Reviews',
    'testimonials.subtitle': 'Thousands of users have reached their financial goals with Sparlo.ai',
    'testimonials.1.name': 'Sarah Johnson',
    'testimonials.1.role': 'Marketing Specialist',
    'testimonials.1.content': 'Thanks to Sparlo.ai, I managed to save $500 monthly. The AI recommendations really work!',
    'testimonials.2.name': 'Michael Brown',
    'testimonials.2.role': 'Software Developer',
    'testimonials.2.content': 'Tracking my expenses has never been this easy. Reaching my goals is now much more achievable.',
    'testimonials.3.name': 'Emily Davis',
    'testimonials.3.role': 'Teacher',
    'testimonials.3.content': 'With its user-friendly interface and detailed analysis, I understand my financial situation much better.',

    // CTA
    'cta.title.1': 'Shape Your Financial',
    'cta.title.2': 'Future Today',
    'cta.description': 'Start smart saving with Sparlo.ai. First 30 days completely free, no credit card required.',
    'cta.start': 'Start Free Trial',
    'cta.chat': 'Live Chat',
    'cta.free': 'Free 30 Days',
    'cta.nocard': 'No Credit Card',
    'cta.instant': 'Instant Setup',

    // Footer
    'footer.description': 'Reach your financial goals with our AI-powered smart savings platform.',
    'footer.pricing': 'Pricing',
    'footer.contact': 'Contact',
    'footer.live': 'Live Support',
    'footer.help': 'Help Center',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy',
    'footer.terms': 'Terms',
    'footer.cookies': 'Cookies',
    'footer.tagline': 'Smart Financial Management for Everyone',

    // Blog
    'blog.financialTips': 'Financial Tips',
    'blog.education': 'Education',
    'blog.news': 'News & Updates',

    // Pricing
    'pricing.free': 'Free Plan',
    'pricing.premium': 'Premium',

    // Login
    'login.title': 'Login to Your Account',
    'login.subtitle': 'Continue your financial journey',
    'login.email': 'Email Address',
    'login.emailPlaceholder': 'example@email.com',
    'login.password': 'Password',
    'login.passwordPlaceholder': 'Enter your password',
    'login.remember': 'Remember me',
    'login.forgot': 'Forgot password',
    'login.submit': 'Login',
    'login.loading': 'Logging in...',
    'login.or': 'or',
    'login.google': 'Login with Google',
    'login.facebook': 'Login with Facebook',
    'login.noAccount': "Don't have an account?",
    'login.register': 'Sign up',
    'login.success': 'Successfully logged in!',
    'login.emailNotFound': 'This email address is not registered.',

    // Register
    'register.title': 'Create Account',
    'register.subtitle': 'Start your journey to financial freedom',
    'register.firstName': 'First Name',
    'register.firstNamePlaceholder': 'Your first name',
    'register.lastName': 'Last Name',
    'register.lastNamePlaceholder': 'Your last name',
    'register.email': 'Email Address',
    'register.emailPlaceholder': 'example@email.com',
    'register.password': 'Password',
    'register.passwordPlaceholder': 'Create a strong password',
    'register.confirmPassword': 'Confirm Password',
    'register.confirmPasswordPlaceholder': 'Re-enter your password',
    'register.terms': 'I agree to the',
    'register.termsLink': 'Terms of Service',
    'register.and': 'and',
    'register.privacyLink': 'Privacy Policy',
    'register.submit': 'Create Account',
    'register.loading': 'Creating account...',
    'register.or': 'or',
    'register.google': 'Sign up with Google',
    'register.facebook': 'Sign up with Facebook',
    'register.hasAccount': 'Already have an account?',
    'register.login': 'Login',
    'register.success': 'Your account has been created successfully!',
    'register.emailExists': 'This email address is already registered.',
    'register.passwordMismatch': 'Passwords do not match.',
    'register.acceptTerms': 'Please accept the terms of service.',

    // Forgot Password
    'forgot.title': 'Forgot Password',
    'forgot.subtitle': "Let's send you a password reset link",
    'forgot.email': 'Email Address',
    'forgot.emailPlaceholder': 'Your registered email address',
    'forgot.submit': 'Send Reset Link',
    'forgot.loading': 'Sending...',
    'forgot.backToLogin': 'Back to login',
    'forgot.successTitle': 'Email Sent',
    'forgot.successMessage': 'Password reset link has been sent to your email address.',
    'forgot.autoClose': 'This window will close automatically...',

    // Partnership
    'partnership.title': 'Our Trusted Partners',
    'partnership.subtitle': 'We work with industry-leading institutions for your financial security',
    'partnership.trustedPartners': 'Trusted Partners',
    'partnership.achievements': 'Our Achievements',
    'partnership.activeUsers': 'Active Users',
    'partnership.totalSavings': 'Total Savings',
    'partnership.uptime': 'Uptime',
    'partnership.support': 'Support',
    'partnership.trustIndicators': 'Trust Indicators',
    'partnership.bankLevel': 'Bank-Level Security',
    'partnership.certified': 'Certified Platform',
    'partnership.encrypted': 'Encrypted Data',
    'partnership.awardWinning': 'Award-Winning Service',

    // Workspace
    'workspace.workspace': 'Workspace',
    'workspace.home': 'Home',
    'workspace.dashboard': 'Dashboard',
    'workspace.templates': 'Templates',
    'workspace.videos': 'Videos',
    'workspace.trash': 'Trash',
    'workspace.library': 'Library',
    'workspace.profile': 'Profile',
    'workspace.pleaseLogin': 'Please Login',
    'workspace.loginRequired': 'Login required to access workspace',
    'workspace.searchPlaceholder': 'Search...',
    'workspace.notifications': 'Notifications',
    'workspace.viewAllNotifications': 'View all notifications',
    'workspace.newTemplate': 'New Template',
    'workspace.profileSettings': 'Profile Settings',
    'workspace.accountSettings': 'Account Settings',
    'workspace.preferences': 'Preferences',
    'workspace.logout': 'Logout',
    'workspace.goToHomePage': 'Go to home page',
    'workspace.clickToGoHome': 'Click to go to home page',
    'workspace.backToHomePage': 'Back to Home Page',

    // Workspace Home
    'workspace.overviewProgress': 'Overview of your progress and recent activities',
    'workspace.whereLeftOff': 'Where You Left Off',
    'workspace.lastActivity': 'Last Activity',
    'workspace.budgetReview': 'Budget review completed',
    'workspace.progressUpdate': 'Progress Update',
    'workspace.improvementThisMonth': 'improvement this month',
    'workspace.comparedToLastMonth': 'compared to last month',
    'workspace.nextRecommendation': 'Next Recommendation',
    'workspace.reviewExpenseCategories': 'Review expense categories',
    'workspace.viewDetails': 'View Details',
    'workspace.monthlyProgress': 'Monthly Progress',
    'workspace.savingsProgress': 'Savings Progress',
    'workspace.goalAchievement': 'Goal Achievement',
    'workspace.budgetAdherence': 'Budget Adherence',
    'workspace.weeklyInsights': 'Weekly Insights',
    'workspace.achievements': 'Achievements',
    'workspace.firstGoalSet': 'First Goal Set',
    'workspace.completedToday': 'Completed today',
    'workspace.savingsStreak': 'Savings Streak',
    'workspace.daysInARow': 'days in a row',
    'workspace.budgetExpert': 'Budget Expert',
    'workspace.under5Budgets': 'under 5 budgets',
    'workspace.quickStats': 'Quick Stats',
    'workspace.totalTransactions': 'Total Transactions',
    'workspace.activeGoals': 'Active Goals',
    'workspace.avgMonthlySavings': 'Avg. Monthly Savings',
    'workspace.bestSavingsMonth': 'Best Savings Month',
    'workspace.thisMonth': 'This Month',
    'workspace.quickActions': 'Quick Actions',
    'workspace.newTemplateCreated': 'New template created',
    'workspace.budgetTemplateCreated': 'Budget template created',
    'workspace.createTemplate': 'Create template',
    'workspace.addTransaction': 'Add Transaction',
    'workspace.trackExpense': 'Track expense',
    'workspace.transactionAdded': 'Transaction added',
    'workspace.expenseTracked': 'Expense tracked',
    'workspace.setGoal': 'Set Goal',
    'workspace.planSavings': 'Plan savings',
    'workspace.goalSet': 'Goal set',
    'workspace.savingsGoalCreated': 'Savings goal created',
    'workspace.addDocument': 'Add Document',
    'workspace.uploadFile': 'Upload file',
    'workspace.documentAdded': 'Document added',
    'workspace.fileUploaded': 'File uploaded',
    'workspace.recentActivities': 'Recent Activities',
    'workspace.noRecentActivities': 'No recent activities',
    'workspace.activitiesThisWeek': 'Activities This Week',
    'workspace.templatesUsed': 'Templates Used',
    'workspace.documentsManaged': 'Documents Managed',
    'workspace.justNow': 'Just now',
    'workspace.minutesAgo': 'minutes ago',
    'workspace.hoursAgo': 'hours ago',
    'workspace.daysAgo': 'days ago',

    // Homepage Sections in Workspace
    'workspace.heroSection': 'Hero Section',
    'workspace.heroSectionDesc': 'Platform introduction and main features',
    'workspace.featuresSection': 'Features',
    'workspace.featuresSectionDesc': 'Detailed description of platform features',
    'workspace.statsSection': 'Statistics',
    'workspace.statsSectionDesc': 'Platform usage statistics',
    'workspace.partnershipSection': 'Partnerships',
    'workspace.partnershipSectionDesc': 'Our trusted business partners',
    'workspace.testimonialsSection': 'User Testimonials',
    'workspace.testimonialsSectionDesc': 'Experiences of our satisfied users',
    'workspace.ctaSection': 'Call to Action',
    'workspace.ctaSectionDesc': 'Encouraging content for platform participation',

    // Templates
    'templates.title': 'Template Gallery',
    'templates.subtitle': 'Ready-made templates for your financial goals',
    'templates.all': 'All',
    'templates.budget': 'Budget',
    'templates.savings': 'Savings',
    'templates.expense': 'Expense',
    'templates.investment': 'Investment',
    'templates.custom': 'Custom',
    'templates.createNew': 'Create New Template',
    'templates.restoreHidden': 'Restore Hidden Templates',
    'templates.noHiddenTemplates': 'No hidden templates found.',
    'templates.confirmRestoreHidden': 'Are you sure you want to restore hidden templates?',
    'templates.noTemplates': 'No templates found',
    'templates.createFirstTemplate': 'Create your first template',
    'templates.templateName': 'Template Name',
    'templates.templateNamePlaceholder': 'Enter template name',
    'templates.description': 'Description',
    'templates.descriptionPlaceholder': 'Enter template description',
    'templates.category': 'Category',
    'templates.create': 'Create',
    'templates.cancel': 'Cancel',
    'templates.useTemplate': 'Use Template',
    'templates.usingTemplate': 'Using template',
    'templates.deleteTemplate': 'Delete template',
    'templates.hideTemplate': 'Hide template',
    'templates.confirmDelete': 'Are you sure you want to delete this template?',
    'templates.confirmDeletePredefined': 'Are you sure you want to hide this predefined template? (You can restore it later)',

    // Predefined Templates
    'templates.monthlyBudget': 'Monthly Budget',
    'templates.monthlyBudgetDesc': 'Track your monthly income and expenses',
    'templates.emergencyFund': 'Emergency Fund',
    'templates.emergencyFundDesc': 'Save for unexpected situations',
    'templates.vacationSavings': 'Vacation Savings',
    'templates.vacationSavingsDesc': 'Save money for your dream vacation',
    'templates.expenseTracker': 'Expense Tracker',
    'templates.expenseTrackerDesc': 'Categorize your daily expenses',
    'templates.investmentPortfolio': 'Investment Portfolio',
    'templates.investmentPortfolioDesc': 'Track and analyze your investments',
    'templates.debtPayoff': 'Debt Payoff',
    'templates.debtPayoffDesc': 'Pay off your debts systematically',

    // Trash
    'trash.title': 'Trash',
    'trash.subtitle': 'You can restore your deleted items from here',
    'trash.autoDeleteWarning': 'Items are automatically deleted after 30 days',
    'trash.empty': 'Trash is empty',
    'trash.emptyDescription': 'Deleted items will appear here',
    'trash.selected': 'selected',
    'trash.selectAll': 'Select all',
    'trash.sortByDeleted': 'Sort by deletion date',
    'trash.sortByName': 'Sort by name',
    'trash.sortByExpiry': 'Sort by expiry date',
    'trash.restoreSelected': 'Restore Selected',
    'trash.deleteSelected': 'Delete Selected',
    'trash.emptyTrash': 'Empty Trash',
    'trash.restore': 'Restore',
    'trash.deleteForever': 'Delete Forever',
    'trash.restored': 'Restored',
    'trash.confirmPermanentDelete': 'Are you sure you want to permanently delete this item?',
    'trash.confirmRestoreSelected': 'Are you sure you want to restore {count} items?',
    'trash.confirmDeleteSelected': 'Are you sure you want to permanently delete {count} items?',
    'trash.confirmEmptyTrash': 'Are you sure you want to empty the trash completely?',
    'trash.deletedOn': 'Deleted:',
    'trash.expiresIn': 'Expires:',
    'trash.expired': 'Expired',
    'trash.days': 'days',
    'trash.hours': 'hours',
    'trash.minutes': 'minutes',

    // Library
    'library.title': 'Resource Library',
    'library.subtitle': 'Financial education and tools',
    'library.searchPlaceholder': 'Search resources...',
    'library.bookmarksOnly': 'Bookmarks only',
    'library.all': 'All',
    'library.guides': 'Guides',
    'library.templates': 'Templates',
    'library.articles': 'Articles',
    'library.videos': 'Videos',
    'library.tools': 'Tools',
    'library.noResults': 'No results found',
    'library.noItems': 'No resources yet',
    'library.tryDifferentSearch': 'Try different search terms',
    'library.addFirstItem': 'Add your first resource',
    'library.opening': 'Opening',
    'library.addNewResource': 'Add New Resource',
    'library.resourceTitle': 'Resource Title',
    'library.resourceTitlePlaceholder': 'Enter resource title',
    'library.description': 'Description',
    'library.descriptionPlaceholder': 'Enter resource description',
    'library.category': 'Category',
    'library.custom': 'Custom',
    'library.resourceType': 'Resource Type',
    'library.typeLink': 'Link',
    'library.typePdf': 'PDF',
    'library.typeDoc': 'Document',
    'library.typeVideo': 'Video',
    'library.typeImage': 'Image',
    'library.typeSpreadsheet': 'Spreadsheet',
    'library.url': 'URL',
    'library.urlPlaceholder': 'https://example.com',
    'library.tags': 'Tags',
    'library.tagsPlaceholder': 'tag1, tag2, tag3',
    'library.cancel': 'Cancel',
    'library.create': 'Create',
    'library.confirmDelete': 'Are you sure you want to delete this resource?',
    'library.confirmRemove': 'Are you sure you want to remove this resource from the library?',
    'library.deleteItem': 'Delete resource',
    'library.removeItem': 'Remove resource',

    // Predefined Library Items
    'library.budgetingGuide': 'Budgeting Guide',
    'library.budgetingGuideDesc': 'Beginner-level budget creation guide',
    'library.investmentBasics': 'Investment Basics',
    'library.investmentBasicsDesc': 'Essential information for entering the investment world',
    'library.retirementCalculator': 'Retirement Calculator',
    'library.retirementCalculatorDesc': 'Calculate how much you need to save for retirement',
    'library.emergencyFundVideo': 'Emergency Fund Video',
    'library.emergencyFundVideoDesc': 'Emergency fund creation strategies',
    'library.taxPlanningGuide': 'Tax Planning Guide',
    'library.taxPlanningGuideDesc': 'Learn how to benefit from tax advantages',
    'library.debtPayoffTemplate': 'Debt Payoff Template',
    'library.debtPayoffTemplateDesc': 'Systematic debt payment plan',

    // Financial Dashboard
    'finDash.totalIncome': 'Total Income',
    'finDash.totalExpense': 'Total Expense',
    'finDash.netSavings': 'Net Savings',
    'finDash.goalsProgress': 'Goals Progress',
    'finDash.thisMonth': 'This month',
    'finDash.savingsRate': 'savings rate',
    'finDash.activeGoals': 'active goals',
    'finDash.recentTransactions': 'Recent Transactions',
    'finDash.savingsGoals': 'Savings Goals',
    'finDash.high': 'High',
    'finDash.medium': 'Medium',
    'finDash.low': 'Low',
    'finDash.completed': 'completed',

    // Profile
    'profile.title': 'User Profile',
    'profile.subtitle': 'Manage your account information',
    'profile.personalInfo': 'Personal Information',
    'profile.password': 'Password',
    'profile.notifications': 'Notifications',
    'profile.privacy': 'Privacy',
    'profile.dataManagement': 'Data Management',
    'profile.firstName': 'First Name',
    'profile.lastName': 'Last Name',
    'profile.email': 'Email',
    'profile.currentPassword': 'Current Password',
    'profile.newPassword': 'New Password',
    'profile.confirmPassword': 'Confirm Password',
    'profile.saveChanges': 'Save Changes',
    'profile.changePassword': 'Change Password',
    'profile.cancel': 'Cancel',
    'profile.successMessage': 'Your information has been updated successfully',
    'profile.errorMessage': 'An error occurred, please try again',
    'profile.passwordMismatch': 'Passwords do not match',
    'profile.passwordChangeSuccess': 'Your password has been changed successfully',
    'profile.passwordChangeError': 'An error occurred while changing password',
    'profile.emailNotifications': 'Email Notifications',
    'profile.emailNotificationsDesc': 'Receive emails for important updates',
    'profile.pushNotifications': 'Push Notifications',
    'profile.pushNotificationsDesc': 'Receive browser notifications',
    'profile.marketingEmails': 'Marketing Emails',
    'profile.marketingEmailsDesc': 'Receive special offers and news',
    'profile.dataSharing': 'Data Sharing',
    'profile.dataSharingDesc': 'Share anonymous usage data',
    'profile.analytics': 'Analytics',
    'profile.analyticsDesc': 'Collect analytics data to improve experience',
    'profile.deleteAccount': 'Delete Account',
    'profile.deleteWarning': 'This action cannot be undone. All your data will be deleted.',
    'profile.dataManagementDesc': 'Manage, export, or delete your data',
    'profile.resetData': 'Reset All Data',
    'profile.resetDataDesc': 'This will delete all your financial data, templates, and settings.',
    'profile.resetDataWarning': 'This action cannot be undone!',
    'profile.whatWillBeDeleted': 'Data to be deleted:',
    'profile.allTransactions': 'All transactions',
    'profile.allGoals': 'All goals',
    'profile.dashboardStats': 'Dashboard statistics',
    'profile.activityHistory': 'Activity history',
    'profile.customTemplates': 'Custom templates',
    'profile.libraryItems': 'Library items',
    'profile.trashItems': 'Trash items',
    'profile.userSettings': 'User settings',
    'profile.resetConfirm': 'ARE YOU SURE YOU WANT TO DELETE ALL YOUR DATA? This action cannot be undone!',
    'profile.resetAllData': 'RESET ALL DATA',
    'profile.resetSuccess': 'All your data has been successfully reset',
    'profile.exportData': 'Export Data',
    'profile.exportDataDesc': 'Download all your data in JSON format',
    'profile.exportDataButton': 'Export Data',
    'profile.importData': 'Import Data',
    'profile.importDataDesc': 'Restore previously exported data',
    'profile.importDataButton': 'Import Data',
  },
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.features': 'Funktionen',
    'nav.stats': 'Statistiken',
    'nav.testimonials': 'Bewertungen',
    'nav.contact': 'Kontakt',
    'nav.login': 'Anmelden',
    'nav.signup': 'Registrieren',
    'nav.logout': 'Abmelden',
    'nav.dashboard': 'Dashboard',
    'nav.settings': 'Einstellungen',

    // Hero Section
    'hero.title.1': 'Intelligentes',
    'hero.title.2': 'Sparen',
    'hero.title.3': 'Gestalte Deine',
    'hero.title.4': 'Zukunft',
    'hero.description': 'Optimiere dein Budget und erreiche deine Ziele mit unserer KI-gestützten Finanzmanagement-Plattform.',
    'hero.cta': 'Kostenlos Starten',
    'hero.dashboard': 'Dashboard',
    'hero.dashboard.title': 'Spar-Fortschritt',
    'hero.dashboard.saved': 'Gespart',
    'hero.dashboard.target': 'Ziel',
    'hero.dashboard.progress': 'Fortschritt',
    'hero.dashboard.completion': 'Abschluss',
    'hero.dashboard.days': 'Tage',
    'hero.dashboard.dayProgress': 'Tag {day}: {currency}{amount} gespart',
    'hero.dashboard.todayAmount': 'Heute: {currency}{amount}',

    // Features
    'features.title': 'Leistungsstarke Funktionen',
    'features.subtitle': 'Alles was du brauchst, um deine finanziellen Ziele zu erreichen',
    'features.ai.title': 'KI-Analyse',
    'features.ai.desc': 'Analysiert deine Ausgabengewohnheiten und bietet personalisierte Empfehlungen',
    'features.analysis.title': 'Detaillierte Analyse',
    'features.analysis.desc': 'Erstellt detaillierte Berichte durch Kategorisierung deiner Einnahmen und Ausgaben',
    'features.goals.title': 'Zielverfolgung',
    'features.goals.desc': 'Setze deine Sparziele und verfolge deinen Fortschritt',
    'features.notifications.title': 'Intelligente Benachrichtigungen',
    'features.notifications.desc': 'Erhalte rechtzeitige Warnungen für wichtige finanzielle Änderungen',
    'features.security.title': 'Sicherheit',
    'features.security.desc': 'Deine Daten sind mit 256-Bit SSL-Verschlüsselung geschützt',
    'features.mobile.title': 'Mobilfreundlich',
    'features.mobile.desc': 'Von jedem Gerät aus zugänglich mit responsivem Design',

    // Stats
    'stats.activeUsers': 'Aktive Benutzer',
    'stats.totalSavings': 'Gesamtersparnisse',
    'stats.customerSatisfaction': 'Kundenzufriedenheit',
    'stats.supportService': 'Support-Service',

    // Testimonials
    'testimonials.title': 'Nutzerbewertungen',
    'testimonials.subtitle': 'Tausende von Nutzern haben ihre finanziellen Ziele mit Sparlo.ai erreicht',
    'testimonials.1.name': 'Anna Schmidt',
    'testimonials.1.role': 'Marketing-Spezialistin',
    'testimonials.1.content': 'Dank Sparlo.ai konnte ich monatlich 400€ sparen. Die KI-Empfehlungen funktionieren wirklich!',
    'testimonials.2.name': 'Thomas Müller',
    'testimonials.2.role': 'Software-Entwickler',
    'testimonials.2.content': 'Die Verfolgung meiner Ausgaben war noch nie so einfach. Meine Ziele zu erreichen ist jetzt viel machbarer.',
    'testimonials.3.name': 'Lisa Weber',
    'testimonials.3.role': 'Lehrerin',
    'testimonials.3.content': 'Mit der benutzerfreundlichen Oberfläche und detaillierten Analysen verstehe ich meine finanzielle Situation viel besser.',

    // CTA
    'cta.title.1': 'Gestalte Deine Finanzielle',
    'cta.title.2': 'Zukunft Heute',
    'cta.description': 'Beginne mit intelligentem Sparen mit Sparlo.ai. Erste 30 Tage völlig kostenlos, keine Kreditkarte erforderlich.',
    'cta.start': 'Kostenlose Testversion',
    'cta.chat': 'Live-Chat',
    'cta.free': 'Kostenlose 30 Tage',
    'cta.nocard': 'Keine Kreditkarte',
    'cta.instant': 'Sofortige Einrichtung',

    // Footer
    'footer.description': 'Erreiche deine finanziellen Ziele mit unserer KI-gestützten intelligenten Spar-Plattform.',
    'footer.pricing': 'Preise',
    'footer.contact': 'Kontakt',
    'footer.live': 'Live-Support',
    'footer.help': 'Hilfe-Center',
    'footer.rights': 'Alle Rechte vorbehalten.',
    'footer.privacy': 'Datenschutz',
    'footer.terms': 'Bedingungen',
    'footer.cookies': 'Cookies',
    'footer.tagline': 'Intelligentes Finanzmanagement für Alle',

    // Blog
    'blog.financialTips': 'Finanztipps',
    'blog.education': 'Bildung',
    'blog.news': 'Nachrichten & Updates',

    // Pricing
    'pricing.free': 'Kostenloser Plan',
    'pricing.premium': 'Premium',

    // Login
    'login.title': 'In Dein Konto Einloggen',
    'login.subtitle': 'Setze deine finanzielle Reise fort',
    'login.email': 'E-Mail-Adresse',
    'login.emailPlaceholder': 'beispiel@email.com',
    'login.password': 'Passwort',
    'login.passwordPlaceholder': 'Gib dein Passwort ein',
    'login.remember': 'Angemeldet bleiben',
    'login.forgot': 'Passwort vergessen',
    'login.submit': 'Anmelden',
    'login.loading': 'Anmeldung läuft...',
    'login.or': 'oder',
    'login.google': 'Mit Google anmelden',
    'login.facebook': 'Mit Facebook anmelden',
    'login.noAccount': 'Noch kein Konto?',
    'login.register': 'Registrieren',
    'login.success': 'Erfolgreich angemeldet!',
    'login.emailNotFound': 'Diese E-Mail-Adresse ist nicht registriert.',

    // Register
    'register.title': 'Konto Erstellen',
    'register.subtitle': 'Beginne deine Reise zur finanziellen Freiheit',
    'register.firstName': 'Vorname',
    'register.firstNamePlaceholder': 'Dein Vorname',
    'register.lastName': 'Nachname',
    'register.lastNamePlaceholder': 'Dein Nachname',
    'register.email': 'E-Mail-Adresse',
    'register.emailPlaceholder': 'beispiel@email.com',
    'register.password': 'Passwort',
    'register.passwordPlaceholder': 'Erstelle ein starkes Passwort',
    'register.confirmPassword': 'Passwort Bestätigen',
    'register.confirmPasswordPlaceholder': 'Gib dein Passwort erneut ein',
    'register.terms': 'Ich stimme den',
    'register.termsLink': 'Nutzungsbedingungen',
    'register.and': 'und der',
    'register.privacyLink': 'Datenschutzrichtlinie',
    'register.submit': 'Konto Erstellen',
    'register.loading': 'Konto wird erstellt...',
    'register.or': 'oder',
    'register.google': 'Mit Google registrieren',
    'register.facebook': 'Mit Facebook registrieren',
    'register.hasAccount': 'Bereits ein Konto?',
    'register.login': 'Anmelden',
    'register.success': 'Dein Konto wurde erfolgreich erstellt!',
    'register.emailExists': 'Diese E-Mail-Adresse ist bereits registriert.',
    'register.passwordMismatch': 'Passwörter stimmen nicht überein.',
    'register.acceptTerms': 'Bitte akzeptiere die Nutzungsbedingungen.',

    // Forgot Password
    'forgot.title': 'Passwort Vergessen',
    'forgot.subtitle': 'Lass uns dir einen Passwort-Reset-Link senden',
    'forgot.email': 'E-Mail-Adresse',
    'forgot.emailPlaceholder': 'Deine registrierte E-Mail-Adresse',
    'forgot.submit': 'Reset-Link Senden',
    'forgot.loading': 'Wird gesendet...',
    'forgot.backToLogin': 'Zurück zur Anmeldung',
    'forgot.successTitle': 'E-Mail Gesendet',
    'forgot.successMessage': 'Passwort-Reset-Link wurde an deine E-Mail-Adresse gesendet.',
    'forgot.autoClose': 'Dieses Fenster schließt sich automatisch...',

    // Partnership
    'partnership.title': 'Unsere Vertrauenswürdigen Partner',
    'partnership.subtitle': 'Wir arbeiten mit branchenführenden Institutionen für deine finanzielle Sicherheit',
    'partnership.trustedPartners': 'Vertrauenswürdige Partner',
    'partnership.achievements': 'Unsere Erfolge',
    'partnership.activeUsers': 'Aktive Benutzer',
    'partnership.totalSavings': 'Gesamtersparnisse',
    'partnership.uptime': 'Betriebszeit',
    'partnership.support': 'Support',
    'partnership.trustIndicators': 'Vertrauensindikatoren',
    'partnership.bankLevel': 'Bank-Level Sicherheit',
    'partnership.certified': 'Zertifizierte Plattform',
    'partnership.encrypted': 'Verschlüsselte Daten',
    'partnership.awardWinning': 'Preisgekrönter Service',

    // Workspace
    'workspace.workspace': 'Arbeitsbereich',
    'workspace.home': 'Startseite',
    'workspace.dashboard': 'Dashboard',
    'workspace.templates': 'Vorlagen',
    'workspace.videos': 'Videos',
    'workspace.trash': 'Papierkorb',
    'workspace.library': 'Bibliothek',
    'workspace.profile': 'Profil',
    'workspace.pleaseLogin': 'Bitte Anmelden',
    'workspace.loginRequired': 'Anmeldung erforderlich für Arbeitsbereich-Zugang',
    'workspace.searchPlaceholder': 'Suchen...',
    'workspace.notifications': 'Benachrichtigungen',
    'workspace.viewAllNotifications': 'Alle Benachrichtigungen anzeigen',
    'workspace.newTemplate': 'Neue Vorlage',
    'workspace.profileSettings': 'Profil-Einstellungen',
    'workspace.accountSettings': 'Konto-Einstellungen',
    'workspace.preferences': 'Einstellungen',
    'workspace.logout': 'Abmelden',
    'workspace.goToHomePage': 'Zur Startseite gehen',
    'workspace.clickToGoHome': 'Klicken um zur Startseite zu gehen',
    'workspace.backToHomePage': 'Zurück zur Startseite',

    // Workspace Home
    'workspace.overviewProgress': 'Überblick über deinen Fortschritt und aktuelle Aktivitäten',
    'workspace.whereLeftOff': 'Wo Du Aufgehört Hast',
    'workspace.lastActivity': 'Letzte Aktivität',
    'workspace.budgetReview': 'Budget-Überprüfung abgeschlossen',
    'workspace.progressUpdate': 'Fortschritts-Update',
    'workspace.improvementThisMonth': 'Verbesserung diesen Monat',
    'workspace.comparedToLastMonth': 'im Vergleich zum letzten Monat',
    'workspace.nextRecommendation': 'Nächste Empfehlung',
    'workspace.reviewExpenseCategories': 'Ausgabenkategorien überprüfen',
    'workspace.viewDetails': 'Details Anzeigen',
    'workspace.monthlyProgress': 'Monatlicher Fortschritt',
    'workspace.savingsProgress': 'Spar-Fortschritt',
    'workspace.goalAchievement': 'Zielerreichung',
    'workspace.budgetAdherence': 'Budget-Einhaltung',
    'workspace.weeklyInsights': 'Wöchentliche Einblicke',
    'workspace.achievements': 'Erfolge',
    'workspace.firstGoalSet': 'Erstes Ziel Gesetzt',
    'workspace.completedToday': 'Heute abgeschlossen',
    'workspace.savingsStreak': 'Spar-Serie',
    'workspace.daysInARow': 'Tage hintereinander',
    'workspace.budgetExpert': 'Budget-Experte',
    'workspace.under5Budgets': 'unter 5 Budgets',
    'workspace.quickStats': 'Schnelle Statistiken',
    'workspace.totalTransactions': 'Gesamte Transaktionen',
    'workspace.activeGoals': 'Aktive Ziele',
    'workspace.avgMonthlySavings': 'Durchschn. Monatliche Ersparnisse',
    'workspace.bestSavingsMonth': 'Bester Spar-Monat',
    'workspace.thisMonth': 'Dieser Monat',
    'workspace.quickActions': 'Schnelle Aktionen',
    'workspace.newTemplateCreated': 'Neue Vorlage erstellt',
    'workspace.budgetTemplateCreated': 'Budget-Vorlage erstellt',
    'workspace.createTemplate': 'Vorlage erstellen',
    'workspace.addTransaction': 'Transaktion Hinzufügen',
    'workspace.trackExpense': 'Ausgabe verfolgen',
    'workspace.transactionAdded': 'Transaktion hinzugefügt',
    'workspace.expenseTracked': 'Ausgabe verfolgt',
    'workspace.setGoal': 'Ziel Setzen',
    'workspace.planSavings': 'Ersparnisse planen',
    'workspace.goalSet': 'Ziel gesetzt',
    'workspace.savingsGoalCreated': 'Sparziel erstellt',
    'workspace.addDocument': 'Dokument Hinzufügen',
    'workspace.uploadFile': 'Datei hochladen',
    'workspace.documentAdded': 'Dokument hinzugefügt',
    'workspace.fileUploaded': 'Datei hochgeladen',
    'workspace.recentActivities': 'Aktuelle Aktivitäten',
    'workspace.noRecentActivities': 'Keine aktuellen Aktivitäten',
    'workspace.activitiesThisWeek': 'Aktivitäten Diese Woche',
    'workspace.templatesUsed': 'Verwendete Vorlagen',
    'workspace.documentsManaged': 'Verwaltete Dokumente',
    'workspace.justNow': 'Gerade eben',
    'workspace.minutesAgo': 'Minuten her',
    'workspace.hoursAgo': 'Stunden her',
    'workspace.daysAgo': 'Tage her',

    // Homepage Sections in Workspace
    'workspace.heroSection': 'Hero-Bereich',
    'workspace.heroSectionDesc': 'Plattform-Einführung und Hauptfunktionen',
    'workspace.featuresSection': 'Funktionen',
    'workspace.featuresSectionDesc': 'Detaillierte Beschreibung der Plattform-Funktionen',
    'workspace.statsSection': 'Statistiken',
    'workspace.statsSectionDesc': 'Plattform-Nutzungsstatistiken',
    'workspace.partnershipSection': 'Partnerschaften',
    'workspace.partnershipSectionDesc': 'Unsere vertrauenswürdigen Geschäftspartner',
    'workspace.testimonialsSection': 'Nutzerbewertungen',
    'workspace.testimonialsSectionDesc': 'Erfahrungen unserer zufriedenen Nutzer',
    'workspace.ctaSection': 'Handlungsaufforderung',
    'workspace.ctaSectionDesc': 'Ermutigender Inhalt für Plattform-Teilnahme',

    // Templates
    'templates.title': 'Vorlagen-Galerie',
    'templates.subtitle': 'Fertige Vorlagen für deine finanziellen Ziele',
    'templates.all': 'Alle',
    'templates.budget': 'Budget',
    'templates.savings': 'Ersparnisse',
    'templates.expense': 'Ausgaben',
    'templates.investment': 'Investition',
    'templates.custom': 'Benutzerdefiniert',
    'templates.createNew': 'Neue Vorlage Erstellen',
    'templates.restoreHidden': 'Versteckte Vorlagen Wiederherstellen',
    'templates.noHiddenTemplates': 'Keine versteckten Vorlagen gefunden.',
    'templates.confirmRestoreHidden': 'Bist du sicher, dass du versteckte Vorlagen wiederherstellen möchtest?',
    'templates.noTemplates': 'Keine Vorlagen gefunden',
    'templates.createFirstTemplate': 'Erstelle deine erste Vorlage',
    'templates.templateName': 'Vorlagen-Name',
    'templates.templateNamePlaceholder': 'Vorlagen-Name eingeben',
    'templates.description': 'Beschreibung',
    'templates.descriptionPlaceholder': 'Vorlagen-Beschreibung eingeben',
    'templates.category': 'Kategorie',
    'templates.create': 'Erstellen',
    'templates.cancel': 'Abbrechen',
    'templates.useTemplate': 'Vorlage Verwenden',
    'templates.usingTemplate': 'Vorlage wird verwendet',
    'templates.deleteTemplate': 'Vorlage löschen',
    'templates.hideTemplate': 'Vorlage verstecken',
    'templates.confirmDelete': 'Bist du sicher, dass du diese Vorlage löschen möchtest?',
    'templates.confirmDeletePredefined': 'Bist du sicher, dass du diese vordefinierte Vorlage verstecken möchtest? (Du kannst sie später wiederherstellen)',

    // Predefined Templates
    'templates.monthlyBudget': 'Monatsbudget',
    'templates.monthlyBudgetDesc': 'Verfolge deine monatlichen Einnahmen und Ausgaben',
    'templates.emergencyFund': 'Notfallfonds',
    'templates.emergencyFundDesc': 'Spare für unerwartete Situationen',
    'templates.vacationSavings': 'Urlaubsersparnisse',
    'templates.vacationSavingsDesc': 'Spare Geld für deinen Traumurlaub',
    'templates.expenseTracker': 'Ausgaben-Tracker',
    'templates.expenseTrackerDesc': 'Kategorisiere deine täglichen Ausgaben',
    'templates.investmentPortfolio': 'Investment-Portfolio',
    'templates.investmentPortfolioDesc': 'Verfolge und analysiere deine Investitionen',
    'templates.debtPayoff': 'Schulden-Tilgung',
    'templates.debtPayoffDesc': 'Zahle deine Schulden systematisch ab',

    // Trash
    'trash.title': 'Papierkorb',
    'trash.subtitle': 'Du kannst deine gelöschten Elemente von hier wiederherstellen',
    'trash.autoDeleteWarning': 'Elemente werden nach 30 Tagen automatisch gelöscht',
    'trash.empty': 'Papierkorb ist leer',
    'trash.emptyDescription': 'Gelöschte Elemente werden hier angezeigt',
    'trash.selected': 'ausgewählt',
    'trash.selectAll': 'Alle auswählen',
    'trash.sortByDeleted': 'Nach Löschdatum sortieren',
    'trash.sortByName': 'Nach Name sortieren',
    'trash.sortByExpiry': 'Nach Ablaufdatum sortieren',
    'trash.restoreSelected': 'Ausgewählte Wiederherstellen',
    'trash.deleteSelected': 'Ausgewählte Löschen',
    'trash.emptyTrash': 'Papierkorb Leeren',
    'trash.restore': 'Wiederherstellen',
    'trash.deleteForever': 'Endgültig Löschen',
    'trash.restored': 'Wiederhergestellt',
    'trash.confirmPermanentDelete': 'Bist du sicher, dass du dieses Element endgültig löschen möchtest?',
    'trash.confirmRestoreSelected': 'Bist du sicher, dass du {count} Elemente wiederherstellen möchtest?',
    'trash.confirmDeleteSelected': 'Bist du sicher, dass du {count} Elemente endgültig löschen möchtest?',
    'trash.confirmEmptyTrash': 'Bist du sicher, dass du den Papierkorb vollständig leeren möchtest?',
    'trash.deletedOn': 'Gelöscht:',
    'trash.expiresIn': 'Läuft ab:',
    'trash.expired': 'Abgelaufen',
    'trash.days': 'Tage',
    'trash.hours': 'Stunden',
    'trash.minutes': 'Minuten',

    // Library
    'library.title': 'Ressourcen-Bibliothek',
    'library.subtitle': 'Finanzbildung und Tools',
    'library.searchPlaceholder': 'Ressourcen durchsuchen...',
    'library.bookmarksOnly': 'Nur Lesezeichen',
    'library.all': 'Alle',
    'library.guides': 'Leitfäden',
    'library.templates': 'Vorlagen',
    'library.articles': 'Artikel',
    'library.videos': 'Videos',
    'library.tools': 'Tools',
    'library.noResults': 'Keine Ergebnisse gefunden',
    'library.noItems': 'Noch keine Ressourcen',
    'library.tryDifferentSearch': 'Versuche andere Suchbegriffe',
    'library.addFirstItem': 'Füge deine erste Ressource hinzu',
    'library.opening': 'Öffnet',
    'library.addNewResource': 'Neue Ressource Hinzufügen',
    'library.resourceTitle': 'Ressourcen-Titel',
    'library.resourceTitlePlaceholder': 'Ressourcen-Titel eingeben',
    'library.description': 'Beschreibung',
    'library.descriptionPlaceholder': 'Ressourcen-Beschreibung eingeben',
    'library.category': 'Kategorie',
    'library.custom': 'Benutzerdefiniert',
    'library.resourceType': 'Ressourcen-Typ',
    'library.typeLink': 'Link',
    'library.typePdf': 'PDF',
    'library.typeDoc': 'Dokument',
    'library.typeVideo': 'Video',
    'library.typeImage': 'Bild',
    'library.typeSpreadsheet': 'Tabellenkalkulation',
    'library.url': 'URL',
    'library.urlPlaceholder': 'https://beispiel.com',
    'library.tags': 'Tags',
    'library.tagsPlaceholder': 'tag1, tag2, tag3',
    'library.cancel': 'Abbrechen',
    'library.create': 'Erstellen',
    'library.confirmDelete': 'Bist du sicher, dass du diese Ressource löschen möchtest?',
    'library.confirmRemove': 'Bist du sicher, dass du diese Ressource aus der Bibliothek entfernen möchtest?',
    'library.deleteItem': 'Ressource löschen',
    'library.removeItem': 'Ressource entfernen',

    // Predefined Library Items
    'library.budgetingGuide': 'Budget-Leitfaden',
    'library.budgetingGuideDesc': 'Anfänger-Level Budget-Erstellungsanleitung',
    'library.investmentBasics': 'Investment-Grundlagen',
    'library.investmentBasicsDesc': 'Wesentliche Informationen für den Einstieg in die Investmentwelt',
    'library.retirementCalculator': 'Renten-Rechner',
    'library.retirementCalculatorDesc': 'Berechne, wie viel du für die Rente sparen musst',
    'library.emergencyFundVideo': 'Notfallfonds-Video',
    'library.emergencyFundVideoDesc': 'Strategien zur Erstellung eines Notfallfonds',
    'library.taxPlanningGuide': 'Steuerplanungs-Leitfaden',
    'library.taxPlanningGuideDesc': 'Lerne, wie du von Steuervorteilen profitieren kannst',
    'library.debtPayoffTemplate': 'Schulden-Tilgungs-Vorlage',
    'library.debtPayoffTemplateDesc': 'Systematischer Schulden-Zahlungsplan',

    // Financial Dashboard
    'finDash.totalIncome': 'Gesamteinkommen',
    'finDash.totalExpense': 'Gesamtausgaben',
    'finDash.netSavings': 'Nettoersparnisse',
    'finDash.goalsProgress': 'Ziel-Fortschritt',
    'finDash.thisMonth': 'Diesen Monat',
    'finDash.savingsRate': 'Sparquote',
    'finDash.activeGoals': 'aktive Ziele',
    'finDash.recentTransactions': 'Aktuelle Transaktionen',
    'finDash.savingsGoals': 'Sparziele',
    'finDash.high': 'Hoch',
    'finDash.medium': 'Mittel',
    'finDash.low': 'Niedrig',
    'finDash.completed': 'abgeschlossen',

    // Profile
    'profile.title': 'Benutzerprofil',
    'profile.subtitle': 'Verwalte deine Kontoinformationen',
    'profile.personalInfo': 'Persönliche Informationen',
    'profile.password': 'Passwort',
    'profile.notifications': 'Benachrichtigungen',
    'profile.privacy': 'Datenschutz',
    'profile.dataManagement': 'Datenverwaltung',
    'profile.firstName': 'Vorname',
    'profile.lastName': 'Nachname',
    'profile.email': 'E-Mail',
    'profile.currentPassword': 'Aktuelles Passwort',
    'profile.newPassword': 'Neues Passwort',
    'profile.confirmPassword': 'Passwort Bestätigen',
    'profile.saveChanges': 'Änderungen Speichern',
    'profile.changePassword': 'Passwort Ändern',
    'profile.cancel': 'Abbrechen',
    'profile.successMessage': 'Deine Informationen wurden erfolgreich aktualisiert',
    'profile.errorMessage': 'Ein Fehler ist aufgetreten, bitte versuche es erneut',
    'profile.passwordMismatch': 'Passwörter stimmen nicht überein',
    'profile.passwordChangeSuccess': 'Dein Passwort wurde erfolgreich geändert',
    'profile.passwordChangeError': 'Ein Fehler ist beim Ändern des Passworts aufgetreten',
    'profile.emailNotifications': 'E-Mail-Benachrichtigungen',
    'profile.emailNotificationsDesc': 'Erhalte E-Mails für wichtige Updates',
    'profile.pushNotifications': 'Push-Benachrichtigungen',
    'profile.pushNotificationsDesc': 'Erhalte Browser-Benachrichtigungen',
    'profile.marketingEmails': 'Marketing-E-Mails',
    'profile.marketingEmailsDesc': 'Erhalte spezielle Angebote und Neuigkeiten',
    'profile.dataSharing': 'Datenfreigabe',
    'profile.dataSharingDesc': 'Anonyme Nutzungsdaten teilen',
    'profile.analytics': 'Analytik',
    'profile.analyticsDesc': 'Sammle Analysedaten zur Verbesserung der Erfahrung',
    'profile.deleteAccount': 'Konto Löschen',
    'profile.deleteWarning': 'Diese Aktion kann nicht rückgängig gemacht werden. Alle deine Daten werden gelöscht.',
    'profile.dataManagementDesc': 'Verwalte, exportiere oder lösche deine Daten',
    'profile.resetData': 'Alle Daten Zurücksetzen',
    'profile.resetDataDesc': 'Dies löscht alle deine Finanzdaten, Vorlagen und Einstellungen.',
    'profile.resetDataWarning': 'Diese Aktion kann nicht rückgängig gemacht werden!',
    'profile.whatWillBeDeleted': 'Zu löschende Daten:',
    'profile.allTransactions': 'Alle Transaktionen',
    'profile.allGoals': 'Alle Ziele',
    'profile.dashboardStats': 'Dashboard-Statistiken',
    'profile.activityHistory': 'Aktivitätsverlauf',
    'profile.customTemplates': 'Benutzerdefinierte Vorlagen',
    'profile.libraryItems': 'Bibliotheks-Elemente',
    'profile.trashItems': 'Papierkorb-Elemente',
    'profile.userSettings': 'Benutzereinstellungen',
    'profile.resetConfirm': 'BIST DU SICHER, DASS DU ALLE DEINE DATEN LÖSCHEN MÖCHTEST? Diese Aktion kann nicht rückgängig gemacht werden!',
    'profile.resetAllData': 'ALLE DATEN ZURÜCKSETZEN',
    'profile.resetSuccess': 'Alle deine Daten wurden erfolgreich zurückgesetzt',
    'profile.exportData': 'Daten Exportieren',
    'profile.exportDataDesc': 'Lade alle deine Daten im JSON-Format herunter',
    'profile.exportDataButton': 'Daten Exportieren',
    'profile.importData': 'Daten Importieren',
    'profile.importDataDesc': 'Stelle zuvor exportierte Daten wieder her',
    'profile.importDataButton': 'Daten Importieren',
  }
};

const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('tr');
  const [resetKey, setResetKey] = useState(0);

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['tr', 'en', 'de'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleLanguageChange = (newLanguage: Language) => {
    setLanguage(newLanguage);
    localStorage.setItem('language', newLanguage);
    setResetKey(prev => prev + 1);
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    let translation = translations[language][key as keyof typeof translations[typeof language]] || key;
    
    if (params) {
      Object.entries(params).forEach(([paramKey, paramValue]) => {
        translation = translation.replace(`{${paramKey}}`, String(paramValue));
      });
    }
    
    return translation;
  };

  const getCurrency = (): string => {
    switch (language) {
      case 'tr': return '₺';
      case 'en': return '$';
      case 'de': return '€';
      default: return '₺';
    }
  };

  const value: LanguageContextType = {
    language,
    setLanguage: handleLanguageChange,
    t,
    currency: getCurrency(),
    resetKey
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export { LanguageProvider };